// <auto-generated />
using System;
using Cms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523224808_update-1")]
    partial class update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cms.Domain.Content.ContentItems.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContentItems", (string)null);
                });

            modelBuilder.Entity("Cms.Domain.Content.ContentItems.ContentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.ToTable("ContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Domain.Content.ContentTypes.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContentTypes", (string)null);
                });

            modelBuilder.Entity("Cms.Domain.Content.ContentItems.ContentItem", b =>
                {
                    b.OwnsMany("Cms.Domain.Content.ContentItems.ContentFieldValue", "Values", b1 =>
                        {
                            b1.Property<Guid>("ContentItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FieldName")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Value");

                            b1.HasKey("ContentItemId", "__synthesizedOrdinal");

                            b1.ToTable("ContentItems");

                            b1
                                .ToJson("Values")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ContentItemId");
                        });

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Cms.Domain.Content.ContentItems.ContentVersion", b =>
                {
                    b.HasOne("Cms.Domain.Content.ContentItems.ContentItem", "ContentItem")
                        .WithMany("Versions")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Cms.Domain.Content.ContentItems.ContentFieldValue", "Values", b1 =>
                        {
                            b1.Property<Guid>("ContentVersionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FieldName")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Value");

                            b1.HasKey("ContentVersionId", "__synthesizedOrdinal");

                            b1.ToTable("ContentVersions");

                            b1
                                .ToJson("Values")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ContentVersionId");
                        });

                    b.Navigation("ContentItem");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Cms.Domain.Content.ContentTypes.ContentType", b =>
                {
                    b.OwnsMany("Cms.Domain.Content.ContentTypes.ContentFieldDefinition", "FieldDefinitions", b1 =>
                        {
                            b1.Property<Guid>("ContentTypeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsRequired");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256);

                            b1.Property<int>("Type");

                            b1.HasKey("ContentTypeId", "__synthesizedOrdinal");

                            b1.ToTable("ContentTypes");

                            b1
                                .ToJson("FieldDefinitions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ContentTypeId");
                        });

                    b.Navigation("FieldDefinitions");
                });

            modelBuilder.Entity("Cms.Domain.Content.ContentItems.ContentItem", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
